### ISSUE TITLE
firefoxProfile object overwrites supplied capabilities

### ISSUE THREAD

**Issue by vbyjsue** [webdriverio/wdio-firefox-profile-service#15]
I'm launching wdio programmatically supplying capabilities for firefox like this:
```
{
  browserName: 'firefox',
  'moz:firefoxOptions': {
    args: ['--width=400', '--height=768']
   }
};
```
This works fine, opening firefox at the correct size. But I also use the wdio-firefox-profile-service to supply a profile and the firefox-profile-launch-service.js overwrites the 'moz:firefoxOptions' like this:
```
cap['moz:firefoxOptions'] = {
  profile: zippedProfile
}
```
If I change firefox-profile-launch-service.js to add the property instead it works:
`cap['moz:firefoxOptions'].profile = zippedProfile;`

**Comment by christian-bromann** [comment]
Let's continue our convo in #16
