### ISSUE TITLE
Cannot ignore certificate errors in firefox profile service

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-firefox-profile-service#17]
_From @Nandish47 on July 5, 2018 6:57_

## The problem

Hi,

I tried to ignore a firefox certificate error 'Your connection is not secure' which usually occurs if certificate is not trusted by using wdio-firefox-profile-service from wdio.conf.js.

services: ['firefox-profile'],

firefoxProfile: {
    assumeUntrustedCertIssuer: true,
    canAssumeUntrustedCertIssuer: true
},

But WebdriverIO fails to get past these errors. Are the key values ignoring certificates changed?

## Environment

* WebdriverIO version: ^2.0.2
* Node.js version: v8.11.2
* if wdio testrunner, running synchronous or asynchronous tests: running synchronous 
* Additional wdio packages used (if applicable):
 wdio-firefox-profile-service: ^0.1.2

_Copied from original issue: webdriverio/webdriverio#2791_

**Comment by christian-bromann** [comment]
@Nandish47 feel free to provide a fix

**Comment by Nandish47** [comment]
Mr. Bromann,

I found a fix for this issue. But it was not via wdio-firefox-profile-service but wdio.conf.js capabilities by setting option acceptInsecureCerts to true

```
capabilities: [
        {
            // maxInstances can get overwritten per capability. So if you have an in-house Selenium
            // grid with only 5 firefox instances available you can make sure that not more than
            // 5 instances get started at a time.
            maxInstances: 1,
            //
            browserName: 'firefox',
            acceptInsecureCerts : true,
        },
]
```
