### ISSUE TITLE
test command

### ISSUE THREAD

**Issue by KarateCowboy** [webdriverio/wdio-firefox-profile-service#2]
Hello webdriverioskis

I copied this repository and started changing everything from 'firefox' to 'chrome'.

My question is about the npm test command:

```
    "test": "wdio test/wdio.conf.js"
```

Could you please explain in a paragrah to me the nature of this test? I do not understand it.

**Comment by christian-bromann** [comment]
It is basically an integrations tests that runs a [config file](https://github.com/webdriverio/wdio-firefox-profile-service/blob/master/test/wdio.conf.js) in the test directory. This config file uses the service to embed a firefox extension that changes the text on our website and in [the test](https://github.com/webdriverio/wdio-firefox-profile-service/blob/master/test/test.spec.js#L11) I check if this got applied. If that is true I can assume the extension got installed successfully.

**Comment by KarateCowboy** [comment]
what is the wdio command? Normally I would expect 'mocha' or 'cucumber', 'jasmine', etc. Do you think I need this to build a chrome-profile-service? If so, how would I replicate this test setup?

**Comment by christian-bromann** [comment]
> what is the wdio command?

It might be a good idea to start with some basics then: http://webdriver.io/guide/testrunner/gettingstarted.html

**Comment by KarateCowboy** [comment]
Ah. Gotcha.

I have been using [chimp](https://github.com/xolvio/chimp) so I was unfamiliar. In the end, I hope to keep using webdriverio through chimp. However, I can read this documentation. Thank you for that. RTM, RTM!
