### ISSUE TITLE
Firefor Profile Service in wdio.conf

### ISSUE THREAD

**Issue by sajidchingchong** [webdriverio/wdio-firefox-profile-service#6]
Referring to:

http://webdriver.io/guide/services/firefox-profile.html

The following conf snippet doesn't work either locally or with some other service say Sauce Labs:

services: ['firefox-profile'],
firefoxProfile: {
    'media.navigator.streams.fake': true,
    'media.navigator.permission.disabled': true
}

**Comment by christian-bromann** [comment]
Can you try the following to see if it works?

```js
    firefoxProfile: {
        'browser.startup.homepage': 'http://webdriver.io'
    },
```

**Comment by sajidchingchong** [comment]
Nopes! It doesn't work.

**Comment by lutostag** [comment]
Not sure if its related, but I've taken it for a spin and I found two things confusing...
It works if you use browser.... like in the examples in this repo.
but if you init a new client (like with upstream wdio examples) the profile is not passed to it.

**Comment by christian-bromann** [comment]
> Nopes! It doesn't work.

A passing build tells me otherwise.

> but if you init a new client (like with upstream wdio examples) the profile is not passed to it.

Do you mean using WebdriverIO in standalone mode? In this case yes it doesn't work, this service is only working for wdio testrunner. In standalone mode you don't need this service.

@sajidchingchong just tried with latest version and it works properly. Make sure to wait till page has loaded as the page load timeout seems to have no affect in this scenario.

**Comment by sajidchingchong** [comment]
I have put the following in my wdio.conf.js:

capabilities: {
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox',
            }
        }
}},

services: ['firefox-profile'],
firefoxProfile: {
'media.navigator.streams.fake': true,
'media.navigator.permission.disabled': true
}

baseUrl: 'https://appr.tc',

And the following in my test file:

browser.url('/r/' + Math.round(Math.random() * 100000000000));

appr.tc asks for camera and microphone access from the user. 'media.navigator.streams.fake' and 'media.navigator.permission.disabled' doesn't allow the pop up to come and uses fake media instead.

For me this thing is not working using webdriverio test runner.

Any help would be appreciated.

**Comment by christian-bromann** [comment]
@sajidchingchong the `capabilities` should be an array

**Comment by agouaillard** [comment]
Thanks christian. It's a little bit late here, but we will test tomorrow morning first thing.

**Comment by sajidchingchong** [comment]
I have tried turning it into an array. Now it looks like:

capabilities: [
{firefox: { desiredCapabilities: { browserName: 'firefox'} }}
],

It is spawning four firefox instances, closing 3 of them down but the profile attributes are not taking any effect.

The following says that the default browser name is firefox: http://webdriver.io/guide/getstarted/configuration.html

I assume that since the capabilities as an array is not the accepted format, thats why is is behaving like that since it is spawning firefox even if I am trying the following:

capabilities: [
{firefox: { desiredCapabilities: { browserName: 'chrome'} }}
],

My earlier configuration was actually based on the following example:

https://github.com/webdriverio/webdriverrtc/blob/master/examples/wdio/wdio.conf.js

where capabilities is specified as a dictionary.

Awaiting feedback ...

**Comment by christian-bromann** [comment]
@sajidchingchong the fact that you are using multiremote was not clear. I took a look into that and indeed there was a bug that I just fixed and released

**Comment by sajidchingchong** [comment]
Should the capabilities be an array or an object?

**Comment by christian-bromann** [comment]
if you use multiremote, then an object
