### ISSUE TITLE
Update to latest firefox-profile package

### ISSUE THREAD

**Issue by ckm2k1** [webdriverio/wdio-firefox-profile-service#7]
Hey folks,

Could you please push an update to this package? You already merged the PR that bumps up firefox-profile to 0.4.6 here: #4 

We'd need to use the latest firefox-profile because it supports Firefox Web Extensions.
We forked the repo temporarily to get around the issue, but it's a poor long term solution, especially because NPM behaves badly when installing from a forked repo (doesn't build correctly).

Thank you!

**Comment by christian-bromann** [comment]
published to `v0.0.2`

**Comment by ckm2k1** [comment]
@christian-bromann Super, thanks!
