### ISSUE TITLE
Breaking change in firefox-profile

### ISSUE THREAD

**Issue by saadtazi** [webdriverio/wdio-firefox-profile-service#8]
Hi,
I am the maintainer of `firefox-profile` package. This is just a heads-up that I am about to publish a new 1.0 package that introduces a breaking change: `Firefox.prototype.encoded(cb)` now expects an error-first callback (`encoded(function (err, base64Profile) {})`). So if you decide to update your package dependencies, you might want to update [this line](https://github.com/webdriverio/wdio-firefox-profile-service/blob/master/lib/firefox-profile-launch-service.js#L52) (... and also handle the error...).

**Comment by christian-bromann** [comment]
@saadtazi thanks for letting me know

**Comment by andriilazebnyi** [comment]
@christian-bromann 
Could you please take a look at https://github.com/webdriverio/wdio-firefox-profile-service/pull/10 ?

**Comment by christian-bromann** [comment]
Let's close this and continue convo in #10
